package com.ouroboros.utils;

import org.bukkit.Material;
import org.bukkit.entity.LivingEntity;
import org.bukkit.inventory.ItemStack;
import org.bukkit.potion.PotionType;

public class XpUtils 
{
	public static int getXp(LivingEntity entity) 
	{
		return switch(entity.getType()) 
		{
			// Boss Mobs
			case ENDER_DRAGON                  -> 1500;
			case WITHER                        -> 2250;
			case WARDEN 					   -> 3500;
			case ELDER_GUARDIAN                -> 2500;
			case ALLAY 						   -> 500;
			
			// Human
			case VILLAGER,WANDERING_TRADER     -> 0;
			// Human Enemy
			case EVOKER,ILLUSIONER,PILLAGER,
			VINDICATOR,WITCH,ZOMBIE_VILLAGER,
			DROWNED                            -> 100;
			// Common/Passive Mobs (Small)
			case BAT,ARMADILLO,BEE,CAT,FROG,
			FOX,DONKEY,LLAMA,MULE,OCELOT,PANDA,
			PARROT,SNIFFER,SQUID,TADPOLE,TURTLE,
			WOLF                               -> 10;
			// Cattle//Common Animals
			case CAMEL,COW,PIG,CHICKEN,COD,
			GLOW_SQUID,GOAT,HORSE,POLAR_BEAR,
			PUFFERFISH,RABBIT,SALMON,SHEEP,
			TRADER_LLAMA,TROPICAL_FISH         -> 15;
			// Uncommon Passive Mobs
			case SNOW_GOLEM,IRON_GOLEM,
			MOOSHROOM,DOLPHIN,AXOLOTL          -> 35;
			// Common Evil Mobs
			case CREEPER,ZOMBIE,SPIDER,
			SKELETON 						   -> 25;
			// Slime
			case SLIME                         -> 15;
			// Uncommon Evil Mobs
			case ENDERMAN,CAVE_SPIDER,GUARDIAN,
			STRAY,HUSK,BOGGED,VEX,GIANT,BREEZE,
			PHANTOM 						   -> 50;
			// Nether
			case BLAZE,MAGMA_CUBE,STRIDER,
			ZOGLIN,PIGLIN,PIGLIN_BRUTE,GHAST,
			WITHER_SKELETON				       -> 150;
			default                            -> 5;
		};
	}
	
	public static int getXp(Material material) 
	{
		return switch (material) 
		{
			// Overworld Variants
			case COAL_ORE,COPPER_ORE,
			LAPIS_ORE,REDSTONE_ORE     	-> 10;
			case IRON_ORE              	-> 15;
			case GOLD_ORE              	-> 20;
			case EMERALD_ORE           	-> 50;
			case DIAMOND_ORE          	-> 100;
			// Nether Variants
			case DEEPSLATE_COAL_ORE,
			DEEPSLATE_COPPER_ORE,
			DEEPSLATE_LAPIS_ORE,
			DEEPSLATE_REDSTONE_ORE     	-> 20;
			case GLOWSTONE 			   	-> 25;
			case DEEPSLATE_IRON_ORE    	-> 30;
			case NETHER_GOLD_ORE, 
			NETHER_QUARTZ_ORE 	       	-> 35;
			case DEEPSLATE_GOLD_ORE    	-> 40;
			case DEEPSLATE_EMERALD_ORE 	-> 75;
			case DEEPSLATE_DIAMOND_ORE 	-> 150;
			case ANCIENT_DEBRIS        	-> 200;
			// Woods
			case OAK_LOG               	-> 10;
			case BIRCH_LOG,DARK_OAK_LOG,
			ACACIA_LOG,SPRUCE_LOG      	-> 15;
			case MANGROVE_LOG          	-> 15;
			case JUNGLE_LOG            	-> 20;
			case CHERRY_LOG 		   	-> 25;
			default 				   	-> 0;
		};
	}
	
	public static int getXp(ItemStack stack) 
	{
		return switch (stack.getType()) 
		{
			// 10XP
			case TORCH,LANTERN,CRAFTING_TABLE,CHAIN,LADDER,ITEM_FRAME,
			GLOW_ITEM_FRAME,PAINTING,FLOWER_POT,DECORATED_POT,BOOKSHELF       			-> 10;
			// 15XP
			case STICK,GOLD_NUGGET,GOLD_INGOT,IRON_NUGGET,BONE_MEAL,
			LEATHER,PAPER,ARROW,BREAD,COOKIE,MUSHROOM_STEW,BEETROOT_SOUP,MELON,
			SHEARS,FLINT_AND_STEEL,WRITABLE_BOOK,RAIL,CHEST,TRAPPED_CHEST,
			REDSTONE_TORCH,LEVER,BARREL,FURNACE,REPEATER,COMPARATOR,OAK_BUTTON,
			STONE_BUTTON,OAK_PRESSURE_PLATE,STONE_PRESSURE_PLATE,
			LIGHT_WEIGHTED_PRESSURE_PLATE,HEAVY_WEIGHTED_PRESSURE_PLATE,
			TRIPWIRE_HOOK,OAK_DOOR,IRON_DOOR,OAK_FENCE_GATE,OAK_TRAPDOOR,
			IRON_TRAPDOOR,TNT,ARMOR_STAND									  			-> 15;
			// 20XP
			case GLASS_BOTTLE,FIREWORK_STAR,BOOK,ENDER_EYE,BLAZE_POWDER,
			SPECTRAL_ARROW,CAKE,PUMPKIN_PIE,RABBIT_STEW,WOODEN_SWORD,BOW,
			WOODEN_SHOVEL,WOODEN_PICKAXE,WOODEN_AXE,WOODEN_HOE,LEATHER_HELMET,
			LEATHER_CHESTPLATE,LEATHER_LEGGINGS,LEATHER_BOOTS,FISHING_ROD     			-> 20;
			// 25XP
			case BLACK_DYE,WHITE_DYE,GRAY_DYE,LIGHT_GRAY_DYE,BROWN_DYE,RED_DYE,
			ORANGE_DYE,YELLOW_DYE,LIME_DYE,GREEN_DYE,CYAN_DYE,BLUE_DYE,LIGHT_BLUE_DYE,
			MAGENTA_DYE,PURPLE_DYE,PINK_DYE,STONE_SWORD,STONE_SHOVEL,STONE_PICKAXE
			,STONE_AXE,STONE_HOE,SHIELD,CHAINMAIL_HELMET,CHAINMAIL_CHESTPLATE,
			CHAINMAIL_LEGGINGS,CHAINMAIL_BOOTS,TURTLE_HELMET 				  			-> 25;
			// 30XP
			case LECTERN,CRAFTER,DISPENSER,DROPPER,DAYLIGHT_DETECTOR,HOPPER,
			LIGHTNING_ROD,CAULDRON,BELL,REDSTONE_LAMP,PISTON,JUKEBOX,OBSERVER 			-> 30;
			// 35XP
			case IRON_SWORD,IRON_SHOVEL,IRON_PICKAXE,IRON_AXE,IRON_HOE,
			IRON_HELMET,IRON_CHESTPLATE,IRON_LEGGINGS,IRON_BOOTS,
			CROSSBOW,MINECART,STONECUTTER,CARTOGRAPHY_TABLE,NOTE_BLOCK,
			FLETCHING_TABLE,SMITHING_TABLE,GRINDSTONE,LOOM,SMOKER,BLAST_FURNACE,
			CAMPFIRE,COMPOSTER,BEEHIVE 										  			-> 35;
			// 40XP
			case GOLDEN_SWORD,GOLDEN_SHOVEL,GOLDEN_PICKAXE,GOLDEN_AXE,
			GOLDEN_HOE,GOLDEN_HELMET,GOLDEN_CHESTPLATE,GOLDEN_LEGGINGS,
			GOLDEN_BOOTS,TIPPED_ARROW 										  			-> 40;
			// 50XP
			case GLISTERING_MELON_SLICE,MAGMA_CREAM,GOLDEN_CARROT,
			GOLDEN_APPLE,BRUSH,LEAD,COMPASS,CLOCK,SPYGLASS,DIAMOND_SWORD,
			DIAMOND_SHOVEL,DIAMOND_PICKAXE,DIAMOND_AXE,DIAMOND_HOE,DIAMOND_HELMET,
			DIAMOND_CHESTPLATE,DIAMOND_LEGGINGS,DIAMOND_BOOTS,MACE  		  			-> 50;
			// 75XP
			case ANVIL,CONDUIT,LODESTONE,ENCHANTING_TABLE,BREWING_STAND       			-> 75;
			// 100XP
			case NETHERITE_SWORD,NETHERITE_SHOVEL,NETHERITE_PICKAXE,
			NETHERITE_AXE,NETHERITE_HOE,NETHERITE_HELMET,NETHERITE_CHESTPLATE,
			NETHERITE_LEGGINGS,NETHERITE_BOOTS,RECOVERY_COMPASS               			-> 100;
			
			default -> 5;
		};
	}
	
	public static int getXp(PotionType potionType) 
	{
		return switch (potionType) 
		{
			case MUNDANE -> 10;
			default -> 5;
		};
	}
}
